export const itemCategoryValues = [
  "vegetables",
  "fruit",
  "bread",
  "dairy",
  "meat",
  "fish",
  "sweets",
  "chocolate",
  "flour_baking",
  "canned",
  "beverages",
  "frozen",
  "pantry",
  "other"
] as const;

export type ItemCategory = (typeof itemCategoryValues)[number];

export function isItemCategory(value: string): value is ItemCategory {
  return (itemCategoryValues as readonly string[]).includes(value);
}

function normalizeForMatch(text: string): string {
  return text
    .trim()
    .toLocaleLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, " ");
}

/** Longer / more specific phrases first so “čokoladni bonboni” hits chocolate before sweets. */
const CATEGORY_RULES: { category: ItemCategory; keywords: string[] }[] = [
  {
    category: "chocolate",
    keywords: [
      "cokolad",
      "chocolate",
      "nutella",
      "nutela",
      "milka",
      "kinder",
      "raffaell",
      "ferrer",
      "praline",
      "temna cokolad",
      "mlecna cokolad"
    ]
  },
  {
    category: "sweets",
    keywords: [
      "sladkarij",
      "bonbon",
      "bombon",
      "candy",
      "sladico",
      "torta",
      "cake",
      "keks",
      "cookie",
      "marmelad",
      "med",
      "marshmallow",
      "licorice",
      "haribo",
      "zeli",
      "gumi "
    ]
  },
  {
    category: "bread",
    keywords: [
      "kruh",
      "bread",
      "baget",
      "baguette",
      "croissant",
      "rozga",
      "struck",
      "strucka",
      "pecivo",
      "bagel",
      "pita ",
      "tortilja",
      "toast",
      "zito ",
      "žito "
    ]
  },
  {
    category: "flour_baking",
    keywords: [
      "moka",
      "flour",
      "meki",
      "droz",
      "drozj",
      "kvas",
      "skrob",
      "starch",
      "koruzna moka",
      "psenicna moka",
      "buckwheat",
      "ajdova"
    ]
  },
  {
    category: "vegetables",
    keywords: [
      "zelenjav",
      "vegetable",
      "solata",
      "korenje",
      "carrot",
      "brokol",
      "cveta",
      "zelje",
      "cabbage",
      "kumar",
      "cucumber",
      "paradiznik",
      "tomato",
      "paprika",
      "pepper",
      "cekina",
      "onion",
      "cesen",
      "cesnj",
      "garlic",
      "krompir",
      "potato",
      "spinac",
      "spinach",
      "buča",
      "buca",
      "grah",
      "beans",
      "redkv",
      "radish",
      "česen",
      "cesnjak",
      "por ",
      "leek",
      "zelena ",
      "celer",
      "celery",
      "čičerika",
      "cicerika",
      "chickpea",
      "cvetača",
      "brokoli",
      "koruza",
      "corn",
      "zelena solata",
      "fižol",
      "fizol"
    ]
  },
  {
    category: "fruit",
    keywords: [
      "sadj",
      "fruit",
      "jabol",
      "apple",
      "banan",
      "pomaranč",
      "orange",
      "limon",
      "lemon",
      "grozdje",
      "grape",
      "jagod",
      "berry",
      "malina",
      "borovnic",
      "blueberry",
      "lubenica",
      "melona",
      "melon",
      "breskev",
      "peach",
      "sliva",
      "plum",
      "cheresh",
      "češnj",
      "cherry",
      "hrušk",
      "pear",
      "limeta",
      "lime",
      "kivi",
      "kiwi",
      "mandarin",
      "ribez",
      "gozdni",
      "fig",
      "smokv",
      "datelj",
      "kokos",
      "coconut",
      "anan",
      "pineapple",
      "granat",
      "pomegranate",
      "avokad",
      "avocado"
    ]
  },
  {
    category: "dairy",
    keywords: [
      "mleko",
      "milk",
      "sir ",
      "sir,",
      "cheese",
      "sirov",
      "maslo",
      "butter",
      "jogurt",
      "yogurt",
      "joghurt",
      "kisla smetana",
      "smetana",
      "cream",
      "skuta",
      "cottage",
      "ricotta",
      "mozzarel",
      "parmezan",
      "cheddar",
      "feta",
      "kefir",
      "probiotic",
      "mascarpone",
      "smotana",
      "smetan",
      "jajc",
      "egg",
      " eggs",
      "eggs"
    ]
  },
  {
    category: "fish",
    keywords: [
      "riba",
      "fish",
      "losos",
      "salmon",
      "tun",
      "tuna",
      "skuša",
      "sardine",
      "postrv",
      "trout",
      "škarp",
      "seafood",
      "morski",
      "kaviar",
      "školjk",
      "calamar",
      "lignji",
      "gamba",
      "kozice",
      "shrimp",
      "rak ",
      " lobster",
      "jastog",
      "ostriga",
      "mussel",
      "mussels",
      "hobotnica",
      "octopus"
    ]
  },
  {
    category: "meat",
    keywords: [
      "meso",
      "meat",
      "piščan",
      "chicken",
      "puran",
      "turkey",
      "rac ",
      "duck",
      "svinj",
      "pork",
      "goved",
      "beef",
      "teleč",
      "veal",
      "jagnjet",
      "lamb",
      "zrezek",
      "steak",
      "rezina slanine",
      "slanina",
      "bacon",
      "klobas",
      "salami",
      "salame",
      "prsut",
      "ham ",
      "šunk",
      "narezek",
      "ground beef",
      "mlet meso",
      "burger ",
      "minced",
      "cevap",
      "ćevap",
      "ćevapi",
      "ćevapčići",
      "ćevapcici"
    ]
  },
  {
    category: "canned",
    keywords: [
      "konzerv",
      "canned",
      "tin ",
      "pasiran",
      "passata",
      "pelat",
      "paradižnik v konzervi",
      "paradiznik v konzervi",
      "jack mackerel",
      "skuša v konzervi",
      "corned",
      "rinfuz",
      "olive",
      "oliv",
      "kapar",
      "capers",
      "ananas v konzervi"
    ]
  },
  {
    category: "beverages",
    keywords: [
      "voda",
      "water",
      "sok ",
      "juice",
      "nektar",
      "limonada",
      "cola",
      "pijača",
      "pijaca",
      " čaj",
      "caj ",
      "tea",
      " kava",
      "kava ",
      "coffee",
      "espresso",
      "capuccino",
      "cappuccino",
      "pivo",
      "beer",
      "vino",
      "wine",
      "šampanj",
      "champagne",
      "energijsk",
      "energy drink",
      "smoothie",
      "sirup",
      "sirup "
    ]
  },
  {
    category: "frozen",
    keywords: [
      "zamrznu",
      "frozen",
      "hlajen",
      "led ",
      "ice cream",
      "sladoled",
      "gelato",
      "zmrzlina",
      "globoki zamrzovalnik",
      "zamrzoval",
      "deep freeze"
    ]
  },
  {
    category: "pantry",
    keywords: [
      "testenin",
      "pasta",
      "špaget",
      "spaghetti",
      "rezanci",
      "riž",
      "rice",
      "oves",
      "oat",
      "musli",
      "granola",
      "kosmiči",
      "cornflakes",
      "müsli",
      "sladkor",
      "sugar",
      "sol ",
      "salt ",
      "olje",
      "oil ",
      "vinegar",
      "kis ",
      "začimb",
      "spice",
      "paprika zač",
      "origano",
      "oregano",
      "bazilika",
      "basil",
      "lovor",
      "kurkuma",
      "kim ",
      "cumin",
      "oreh",
      "nuts",
      "mandlj",
      "almond",
      "indijsk oreščki",
      "cashew",
      "seme ",
      "seeds",
      "chia",
      "kvinoa",
      "quinoa",
      "bulgur",
      "couscous",
      "stročjič",
      "stročji fižol",
      "sojin",
      "soya",
      "soja ",
      "tofu",
      "tempeh",
      "humus",
      "hummus",
      "omaka",
      "pesto",
      "majonez",
      "mayonnaise",
      "kečap",
      "ketchup",
      "gorčica",
      "mustard",
      "wasabi",
      "sirup za palčink",
      "sirup za pancake",
      "neskvik"
    ]
  }
];

export function inferCategoryFromTitle(title: string): ItemCategory {
  const haystack = normalizeForMatch(title);
  if (!haystack) {
    return "other";
  }

  for (const rule of CATEGORY_RULES) {
    for (const kw of rule.keywords) {
      const needle = normalizeForMatch(kw);
      if (needle && haystack.includes(needle)) {
        return rule.category;
      }
    }
  }

  return "other";
}
